### ISSUE TITLE
鱼上钩没反应

### ISSUE THREAD

**Issue by yukiryo** [genshin-matrix/genshin-fishing-toy#1]
窗口化分辨率1920x1080
![image](https://user-images.githubusercontent.com/58250223/201524788-95f77489-9d49-4170-b325-b446ad423926.png)

**Comment by emako** [comment]
尝试把钓鱼条的高度整高一点它太矮了

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/202230881-13dfb028-d1ab-44c6-8119-eb9136137a48.png)

**Comment by yukiryo** [comment]
没有作用
![image](https://user-images.githubusercontent.com/58250223/202595893-b787e3d4-dd2f-4047-b79b-de9879f8fa0d.png)

**Comment by emako** [comment]
我这边测试窗口化分辨率1920x1080是可以的，可能是图像配置不是默认导致。
我先弄个工具dump游戏配置

**Comment by yukiryo** [comment]
全最高，抗锯齿smaa
![image](https://user-images.githubusercontent.com/58250223/202732989-50fa5e1d-e7f4-4554-89db-4fe68d66ce97.png)

**Comment by emako** [comment]
游戏亮度呢

**Comment by emako** [comment]
有自动上钩吧?

**Comment by yukiryo** [comment]
没有

**Comment by emako** [comment]
杀毒软件加一下白名单。。

**Comment by RookieTerry** [comment]
请问releases里面应该下载哪个版本的？

**Comment by emako** [comment]
> 请问releases里面应该下载哪个版本的？

带setup的是安装包，带full的是内置.NET6运行环境，按需选择

**Comment by emako** [comment]
杀软添加后如果还有问题可以reopen issue
