### ISSUE TITLE
每一次启动后钓鱼框的位置设置就会重置，可不可以设置为允许保持上一次的位置呀

### ISSUE THREAD

**Issue by 1332186865** [genshin-matrix/genshin-fishing-toy#2]
这个是正确的位置
JigRect:
  Item1: 851
  Item2: 81
  Item3: 834
  Item4: 100
每次都会重置为
JigRect:
  Item1: -31149
  Item2: -31919
  Item3: 834
  Item4: 100

**Comment by 1332186865** [comment]
还有一个问题，这个框的位置有时候在屏幕外，找都找不到，也没有办法调整

**Comment by emako** [comment]
原神的独占模式有点坑。你是怎么个使用的流程？

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/205411813-a58e5b4e-caa8-4c11-89e9-f51a9b5e698a.png)
> Item1: 851跟Item1: -31149的时候FullScreenWhenSaved是不是都是true？

**Comment by 1332186865** [comment]
我是通过在Yuanshen.exe文件后加‘ -w‘启动参数的方式启动原神的，之后启动钓鱼姬，调整钓鱼框位置(框的位置很随缘，有时在游戏里，有时在桌面，游戏和桌面分辨率均为2560x1440)，开始钓鱼。有时候钓鱼框不在游戏中显示，我用alt+enter转化为窗口调整位置后再用alt+enter转为全屏也能正常运行。

FullScreenWhenSaved在设置钓鱼框锁定时是True，解锁时也是True，但在解锁并调整钓鱼框位置和大小后变成了False。


JigRect:
  Item1: -31098
  Item2: -31909
  Item3: 686
  Item4: 100
FullScreenWhenSaved: true
Language: ''
Lock: false
ShowRecognitionJigging: false
ShortcutKey: F11
AutoLifting: true
ShowRecognitionLifting: false
这个是打开游戏后打开钓鱼姬后的配置文件
点了重置钓鱼框后配置未改变

JigRect:
  Item1: 858
  Item2: 105
  Item3: 781
  Item4: 100
FullScreenWhenSaved: true
Language: ''
Lock: false
ShowRecognitionJigging: false
ShortcutKey: F11
AutoLifting: true
ShowRecognitionLifting: false
这个是调整位置后的配置

Language: ''
JigRect:
  Item1: -31117
  Item2: -31912
  Item3: 781
  Item4: 100
FullScreenWhenSaved: true
ShortcutKey: F11
AutoLifting: true
ShowRecognitionLifting: false
Lock: false
ShowRecognitionJigging: false
这个是保持原神运行，重启钓鱼姬后的配置文件

JigRect:
  Item1: 864
  Item2: 90
  Item3: 721
  Item4: 100
AutoLifting: true
Lock: false
ShowRecognitionLifting: false
FullScreenWhenSaved: true
Language: ''
ShowRecognitionJigging: false
ShortcutKey: F11
这个是调整钓鱼框位置后，关闭原神，钓鱼姬的配置文件

**Comment by emako** [comment]
目前软件区分全屏非全屏保存，似乎是全屏检测出了点问题。

> Yuanshen.exe -w

这个`-w`是什么参数？

**Comment by 1332186865** [comment]
我原来希望用这个使原神窗口化运行，但后来发现原神还是全屏运行，之后我找到了方法(alt+enter)就忘记删了

我直接点Yuanshen.exe启动游戏，保持原神运行，启动钓鱼姬并调整为正确位置，关闭钓鱼姬后再次打开，钓鱼框的位置仍然不正确（FullScreenWhenSaved一直是真），我猜可能不是这个的问题

**Comment by emako** [comment]
可以尝试先启动钓鱼姬再启动游戏。
或者`alt+enter`窗口化后再启动钓鱼姬。

**Comment by emako** [comment]
### 汇总一下独占模式的问题

#### 独占模式下的正常操作流程：

> 1. 启动游戏进程->启动钓鱼姬->退出钓鱼姬->退出游戏进程

#### 独占模式下存在问题的流程：

> 1. 启动钓鱼姬->启动游戏进程->退出钓鱼姬->退出游戏进程（无法恢复钓鱼框位置并变成类似-31117的值）
> 2. 启动游戏进程->启动钓鱼姬->退出游戏进程->退出钓鱼姬（游戏退出瞬间可能会误识别为窗口模式）

---

未解决前建议全程使用窗口模式钓鱼。

**Comment by 1332186865** [comment]
好滴，谢谢你啦
